### ISSUE TITLE
2023 Oct 25 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by rikoe** [finos/technical-oversight-committee#100]
## Date
2023 Oct 25 - 12:00 EST

### Zoom Info
- Meeting link: https://zoom.us/j/93181085065
- Meeting number: 931 8108 5065
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Discuss TOC voting process
- [x] Discuss TOC candidates
- [x] Backlog review - https://github.com/orgs/finos/projects/39
- [x] Review [TOC responsibilities](https://github.com/finos/technical-oversight-committee/blob/master/responsibilities.md)
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- Voting process and candidates discussed
  - Regarding board vs. TOC vote, the suggestion was made to still include board electee in TOC voting list, and just use the second preference candidate in case the TOC votes for the same candidate as the board (that way the board vote can stay secret until both votes are announced)
  - Variety should be encouraged - in membership, industry sectors, regions and especially in diversity
  - Gender representation should not drive the selection, it should be on merit, but FINOS should look at how to make the pool of candidates more diverse in future
    - One suggestion: Ask all member firms to put candidates forward, emphasising diversity & inclusion
- Backlog review
  - Some issues can be closed, https://github.com/orgs/finos/projects/39/views/1?pane=issue&itemId=20709216 moved back to suggestion since not currently in progress
- TOC Responsibilities
  - To be reviewed at next meeting, including how to ensure equal division of labour, and all tasks are covered

## Actions
- [x] @rikoe - Comment and close https://github.com/finos/community/issues/203
- [x] @maoo - Update activation docs to link to https://github.com/finos/community/issues/203
- [x] @brunodom - Comment on https://github.com/finos/community/issues/277 that TOC review is complete
- [x] @rikoe - Send a chaser email asking for TOC volunteer to review https://github.com/finos/community/issues/215
- [ ] everyone - Review TOC Responsibilities ahead of next meeting, make main discussion point for next meeting

**Comment by rikoe** [comment]
Riko / Adaptive

**Comment by maoo** [comment]
Maurizio / FINOS

**Comment by eminty69** [comment]
Elspeth / RBC CM

**Comment by opoupeney** [comment]
Olivier / Orkes

**Comment by jonfreedman** [comment]
Jon / Brevan Howard
