### ISSUE TITLE
2023 Aug 02 - Technical Oversight Committee Meeting Minutes

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/technical-oversight-committee#76]
### Zoom Info
(Wednesday Meeting)
- Meeting link: https://zoom.us/j/93181085065
- Meeting number: 931 8108 5065
- Password: Check the email invite
- Call-in: Find your local number https://zoom.us/u/abk6zPS0y5

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [ ] @brunodom to share [Accessibility Theme Builder Contribution](https://github.com/finos/community/issues/273) review
  - [ ] approve/reject contribution
- [x] @maoo Discuss outcome of FINOS board meeting (3mins)
  - [x] looking for volunteer to review https://github.com/finos/technical-oversight-committee/pull/78
- [x] @maoo Discuss / raise awareness of the changes that are being made in order to transition from TSC to TOC - https://github.com/finos/community/issues/275 (2mins)
- [x] @maoo Heads up, new contribution https://github.com/finos/community/issues/277 (2mins)
- [x] @maoo looking for volunteers (10mins - if time allows)
  - [ ] Solicit and recommend cross-project synergies
  - [ ] Review of project health
  - [ ] Review of project alignment with FINOS strategy
  - [ ] Identify use-cases / areas of interest (to bring in front of Board of Directors)
  - [ ] Provide strategic input based on existing landscape components
- [ ] AOB, Q&A & Adjourn (5mins)

## Minutes
- [x] Bruno could not join, but shared his notes on A11Y theme builder via email, see https://lists.finos.org/g/toc/messages
- [x] README includes tsc@lists.finos.org - mao will fix
- [x] Riko and Elspeth volunteer on Traderx contribution, after summer break
- [x] We need to formalise approach to tackle new responsibilities (see `responsibilities.md`) and to set KPIs ; created https://github.com/finos/technical-oversight-committee/discussions/79

## Action Items
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by rikoe** [comment]
Here 👋

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by caradelia** [comment]
Cara Delia / RedHat

**Comment by jonfreedman** [comment]
Yo
